version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  ci-cd:
    container_name: express
    image: valiantsin2022/express:latest
    build: .
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"