name: Release NodeJS app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Login to Docker Hub
          uses: actions/checkout@v3
        # We need to login so we can later push the image without issues.
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Builds devopsdockeruh/docker-hy.github.io
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: valiantsin2022/express:latest
